FROM golang:1.24.13-trixie@sha256:5835f052b784aa39f2fe9070def3568605c8bc3fcd810f10402066348b61e716 AS build

RUN apt-get update -y && \
    apt-get install -y rsync

WORKDIR /app/

COPY ./avalanchego /app/avalanchego
COPY ./config /app/config
COPY ./coreth /app/coreth
COPY ./titan-network /app/titan-network

WORKDIR /app/avalanchego/

RUN /app/avalanchego/scripts/build-titan.sh

RUN mkdir -p /app/conf/C /app/keys /app/logs /app/db /app/data

WORKDIR /entrypoint
COPY entrypoint/main.go .
RUN go build -ldflags="-s -w" -o /out/entrypoint main.go

FROM gcr.io/distroless/base:nonroot@sha256:e00da4d3bd422820880b080115b3bad24349bef37ed46d68ed0d13e150dc8d67 AS final

USER nonroot

WORKDIR /app

ENV NODE_MODE="" \
    HTTP_HOST=0.0.0.0 \
    HTTP_PORT=9650 \
    STAKING_PORT=9651 \
    PUBLIC_IP= \
    DATA_DIR=/app/data \
    DB_DIR=/app/db \
    DB_TYPE=leveldb \
    BOOTSTRAP_IPS= \
    BOOTSTRAP_IDS= \
    CHAIN_CONFIG_DIR=/app/conf \
    LOG_DIR=/app/logs \
    LOG_LEVEL=info \
    NETWORK_ID=titan \
    STAKING_TLS_CERT_FILE=/app/keys/staker.crt \
    STAKING_TLS_KEY_FILE=/app/keys/staker.key \
    STAKING_SIGNER_KEY_FILE=/app/keys/signer.key \
    AUTOCONFIGURE_PUBLIC_IP=1 \
    AUTOCONFIGURE_BOOTSTRAP=0 \
    AUTOCONFIGURE_BOOTSTRAP_ENDPOINT= \
    EXTRA_ARGUMENTS="" \
    BOOTSTRAP_BEACON_CONNECTION_TIMEOUT="1m" \
    HTTP_ALLOWED_HOSTS="*"

COPY --from=build --chown=nonroot:nonroot /app/conf /app/conf
COPY --from=build --chown=nonroot:nonroot /app/logs /app/logs
COPY --from=build --chown=nonroot:nonroot /app/db   /app/db

COPY --from=build --chown=nonroot:nonroot /app/avalanchego/build /app/build
COPY --from=build --chown=nonroot:nonroot /out/entrypoint /app/entrypoint

EXPOSE ${STAKING_PORT}
EXPOSE ${HTTP_PORT}

VOLUME [ "${DB_DIR}" ]
VOLUME [ "${LOG_DIR}" ]
VOLUME [ "${CHAIN_CONFIG_DIR}" ]
VOLUME [ "/app/keys" ]

ENTRYPOINT [ "/app/entrypoint" ]
